### ISSUE TITLE
nil pointer dereference panic in system.Connect during startup

### ISSUE THREAD

**Issue by ron1** [noobaa/noobaa-operator#141]
NooBaa 2.0.6
Custom service-mgmt.yaml and service-s3.yaml resources applied without openshift annotation

Work-around: Defer NooBaa CR application until all other resources are applied and noobaa-operator is "Running"

nil point dereference panic in system.Connect during startup here https://github.com/noobaa/noobaa-operator/blob/6725061f60b31707fe326617d08ea1f04f3fce84/pkg/system/system.go#L601

```
...
noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x131a5f8]

goroutine 355 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1722660, 0x28b4fd0)
    /usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
github.com/noobaa/noobaa-operator/v2/pkg/system.Connect(0x1952600, 0x5, 0x1971ca4, 0x1b)
    noobaa-operator/pkg/system/system.go:601 +0x208
github.com/noobaa/noobaa-operator/v2/pkg/backingstore.(*Reconciler).ReadSystemInfo(0xc000c1e0c0, 0x1958e9a, 0xa)
    noobaa-operator/pkg/backingstore/reconciler.go:341 +0x3b
github.com/noobaa/noobaa-operator/v2/pkg/backingstore.(*Reconciler).ReconcilePhaseConnecting(0xc000c1e0c0, 0x0, 0x0)
    noobaa-operator/pkg/backingstore/reconciler.go:229 +0x7c
...
```

**Comment by guymguym** [comment]
Fixed in #128 and released in v2.0.7
Sorry for the hassle

**Comment by ron1** [comment]
Do you think this is the same problem?

**Comment by guymguym** [comment]
yikes, I mixed up completely. it's not related.

**Comment by guymguym** [comment]
@ron1 I introduced this issue recently in https://github.com/noobaa/noobaa-operator/pull/124/commits/502f4c5ba7e3ca5439f6877795dd49a03b03049d
