### ISSUE TITLE
CLI running as root user panic: could not locate a kubeconfig

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-operator#239]
Tested this flow - 
https://github.com/noobaa/noobaa-operator/blob/master/doc/install-on-minikube-on-ubuntu.md

When running `noobaa install` as a normal user it works, but running as root user fails:
```
root@gubuntu:~# noobaa status
INFO[0000] CLI version: 2.0.10
INFO[0000] noobaa-image: noobaa/noobaa-core:5.2.13
INFO[0000] operator-image: noobaa/noobaa-operator:2.0.10
INFO[0000] Namespace: noobaa
INFO[0000]
INFO[0000] CRD Status:
PANI[0000] ☠️  Panic Attack: [] could not locate a kubeconfig
panic: (*logrus.Entry) (0x1944160,0xc00018f9d0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000ea150, 0xc00040c2d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2db
github.com/sirupsen/logrus.(*Entry).Log(0xc000175b90, 0x0, 0xc0006f58c8, 0x1, 0x1)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Entry).Logf(0xc000175b90, 0x0, 0x1992e93, 0x1d, 0xc0006f5928, 0x2, 0x2)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:314 +0xe2
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:352
github.com/noobaa/noobaa-operator/v2/pkg/util.Panic(0x1c4c820, 0xc000303f10)
	noobaa-operator/pkg/util/util.go:490 +0xf3
github.com/noobaa/noobaa-operator/v2/pkg/util.KubeConfig(0x203000)
	noobaa-operator/pkg/util/util.go:83 +0x6e
github.com/noobaa/noobaa-operator/v2/pkg/util.KubeClient(0xc0006f5a78, 0x40be26)
	noobaa-operator/pkg/util/util.go:118 +0x52
github.com/noobaa/noobaa-operator/v2/pkg/util.KubeCheck(0x1c60200, 0xc0000ee2c0, 0xc00019b600)
	noobaa-operator/pkg/util/util.go:291 +0x37
github.com/noobaa/noobaa-operator/v2/pkg/crd.CheckCRD(0xc0000ee2c0)
	noobaa-operator/pkg/crd/crd.go:171 +0x73
github.com/noobaa/noobaa-operator/v2/pkg/crd.ForEachCRD(0x1a387c0)
	noobaa-operator/pkg/crd/crd.go:153 +0x55
github.com/noobaa/noobaa-operator/v2/pkg/crd.RunStatus(...)
	noobaa-operator/pkg/crd/crd.go:110
github.com/noobaa/noobaa-operator/v2/pkg/install.RunStatus(0xc0004f9180, 0x291f9b0, 0x0, 0x0)
	noobaa-operator/pkg/install/install.go:104 +0x181
github.com/spf13/cobra.(*Command).execute(0xc0004f9180, 0x291f9b0, 0x0, 0x0, 0xc0004f9180, 0x291f9b0)
	noobaa-operator/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004f8500, 0x0, 0x0, 0x0)
	noobaa-operator/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	noobaa-operator/vendor/github.com/spf13/cobra/command.go:864
github.com/noobaa/noobaa-operator/v2/pkg/cli.Run()
	noobaa-operator/pkg/cli/cli.go:54 +0x27
main.main()
	noobaa-operator/cmd/manager/main.go:14 +0x20
```

**Comment by hanqingwu** [comment]
may be you should check  root    $HOME .minikube & .kube  both are  correct ?

**Comment by guymguym** [comment]
Thanks @hanqingwu 
I know that root doesn't have a kubeconfig, just wanted the CLI to avoid a panic in that case and write a clearer error message.
