### ISSUE TITLE
install noobaa on OpenPAI created Kubernetes cluster failed

### ISSUE THREAD

**Issue by wpfnihao** [noobaa/noobaa-operator#265]
**Description:**
I have an exisiting [OpenPAI](https://github.com/microsoft/pai) cluster, and I try to deploy Noobaa on it with noobaa-operator, I got the following panic:
```
INFO[0000] CLI version: 2.0.9
INFO[0000] noobaa-image: noobaa/noobaa-core:5.2.11
INFO[0000] operator-image: noobaa/noobaa-operator:2.0.9
INFO[0000] Namespace: default
INFO[0000]
INFO[0000] CRD Create:
INFO[0000] ✅ Already Exists: CustomResourceDefinition "noobaas.noobaa.io"
INFO[0000] ✅ Already Exists: CustomResourceDefinition "backingstores.noobaa.io"
INFO[0000] ✅ Already Exists: CustomResourceDefinition "bucketclasses.noobaa.io"
PANI[0000] ☠️  Panic Attack: [Invalid] CustomResourceDefinition.apiextensions.k8s.io "objectbucketclaims.objectbucket.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[additionalConfig].additionalProperties: Forbidden: additionalProperties cannot be set to false
panic: (*logrus.Entry) (0x1944160,0xc0000a2230)goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000d8150, 0xc0003d6510, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2db
github.com/sirupsen/logrus.(*Entry).Log(0xc000147960, 0x0, 0xc0007fda00, 0x1, 0x1)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Entry).Logf(0xc000147960, 0x0, 0x1992e7d, 0x1d, 0xc0007fda60, 0x2, 0x2)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:314 +0xe2
github.com/sirupsen/logrus.(*Entry).Panicf(...)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:352
github.com/noobaa/noobaa-operator/v2/pkg/util.Panic(0x1c4e260, 0xc000123d40)
        noobaa-operator/pkg/util/util.go:490 +0xf3
github.com/noobaa/noobaa-operator/v2/pkg/util.KubeCreateSkipExisting(0x1c60220, 0xc00039ab00, 0xc0004e7c00)
        noobaa-operator/pkg/util/util.go:210 +0x628
github.com/noobaa/noobaa-operator/v2/pkg/crd.CreateCRD(0xc00039ab00)
        noobaa-operator/pkg/crd/crd.go:159 +0x37
github.com/noobaa/noobaa-operator/v2/pkg/crd.ForEachCRD(0x1a387e0)
        noobaa-operator/pkg/crd/crd.go:153 +0x55
github.com/noobaa/noobaa-operator/v2/pkg/crd.RunCreate(...)
        noobaa-operator/pkg/crd/crd.go:100
github.com/noobaa/noobaa-operator/v2/pkg/install.RunInstall(0xc000621400, 0x291f9b0, 0x0, 0x0)
        noobaa-operator/pkg/install/install.go:56 +0x158
github.com/spf13/cobra.(*Command).execute(0xc000621400, 0x291f9b0, 0x0, 0x0, 0xc000621400, 0x291f9b0)
        noobaa-operator/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000620c80, 0x0, 0x0, 0x0)
        noobaa-operator/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        noobaa-operator/vendor/github.com/spf13/cobra/command.go:864
github.com/noobaa/noobaa-operator/v2/pkg/cli.Run()
        noobaa-operator/pkg/cli/cli.go:54 +0x27
main.main()
        noobaa-operator/cmd/manager/main.go:14 +0x20
```

I also tried deploy noobaa on K8s cluster created by Kind, it works fine.

**Comment by guymguym** [comment]
Hi @wpfnihao 
Not sure what is getting mixed up there.
Can you try to create that CRD manually to figure out thee issue?
```
kubectl create -f https://raw.githubusercontent.com/noobaa/noobaa-operator/v2.0.9/deploy/obc/objectbucket_v1alpha1_objectbucketclaim_crd.yaml
```
I think also the latest version of the CRD on master is identical but you can try too:
```
kubectl create -f https://raw.githubusercontent.com/noobaa/noobaa-operator/master/deploy/obc/objectbucket.io_objectbucketclaims_crd.yaml
```
Let me know what you find
Thanks
