### ISSUE TITLE
BackingStore :Error when s3 endpoint field is not specified

### ISSUE THREAD

**Issue by pranavgaikwad** [noobaa/noobaa-operator#38]
Following Documentation page and CRD here : https://github.com/noobaa/noobaa-operator/blob/e8b5515ffff761eaef11bfe1cbcb05e7a150797b/deploy/crds/noobaa_v1alpha1_backingstore_crd.yaml#L78

**Issue :**

Reconciler of BackingStore results in an error when `endpoint` field is not specified in the CR defn. 

 Here : https://github.com/noobaa/noobaa-operator/blob/e8b5515ffff761eaef11bfe1cbcb05e7a150797b/pkg/backingstore/reconciler.go#L299

**Expected**
BackingStore should assume default S3 URL when type is `aws-s3` and endpoint is not specified

**Error :**
```
E0826 19:45:27.597689       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.12.9/libexec/src/runtime/panic.go:522
/usr/local/Cellar/go/1.12.9/libexec/src/runtime/panic.go:82
/usr/local/Cellar/go/1.12.9/libexec/src/runtime/signal_unix.go:390
noobaa-operator/pkg/backingstore/reconciler.go:299
noobaa-operator/pkg/backingstore/reconciler.go:239
noobaa-operator/pkg/backingstore/reconciler.go:148
noobaa-operator/pkg/backingstore/reconciler.go:107
noobaa-operator/pkg/controller/backingstore/backingstore_controller.go:28
noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:92
noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/Cellar/go/1.12.9/libexec/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12ed262]

goroutine 396 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x16e0ea0, 0x2a48b10)
        /usr/local/Cellar/go/1.12.9/libexec/src/runtime/panic.go:522 +0x1b5
github.com/noobaa/noobaa-operator/pkg/backingstore.(*Reconciler).MakeExternalConnectionParams(0xc00028e900, 0xc000561880, 0x2, 0x4)
        noobaa-operator/pkg/backingstore/reconciler.go:299 +0xf2
github.com/noobaa/noobaa-operator/pkg/backingstore.(*Reconciler).ReadSystemInfo(0xc00028e900, 0x18e89a4, 0xa)
        noobaa-operator/pkg/backingstore/reconciler.go:239 +0x19e
github.com/noobaa/noobaa-operator/pkg/backingstore.(*Reconciler).ReconcilePhases(0xc00028e900, 0xc0000cc500, 0x18e7801)
        noobaa-operator/pkg/backingstore/reconciler.go:148 +0x9d
github.com/noobaa/noobaa-operator/pkg/backingstore.(*Reconciler).Reconcile(0xc00028e900, 0x6, 0xc0007a3e90, 0xc, 0x1c30520)
        noobaa-operator/pkg/backingstore/reconciler.go:107 +0x4c6
github.com/noobaa/noobaa-operator/pkg/controller/backingstore.Add.func1(0xc0007a3eaa, 0x6, 0xc0007a3e90, 0xc, 0xc0009485d0, 0xc000d04d88, 0x18, 0xc000d04d80)
        noobaa-operator/pkg/controller/backingstore/backingstore_controller.go:28 +0x113
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc00024c040, 0xc0007a3eaa, 0x6, 0xc0007a3e90, 0xc, 0x2a63fe0, 0x3, 0x3, 0x2000000000001)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:92 +0x4e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000c4280, 0x0)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x1cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0004832d0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004832d0, 0x3b9aca00, 0x0, 0x1, 0xc0004d41e0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0004832d0, 0x3b9aca00, 0xc0004d41e0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x311
```

**Reproduce :**
Create a secret with S3 credentials. Create following CR : 

```
apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: bstore-s3-00
  labels:
    app: noobaa
    type: aws-s3
  finalizers:
    - noobaa.io/finalizer
spec:
  type: aws-s3
  bucketName: <bucket>
  secret:
    name: aws-s3-00
    namespace: noobaa
``` 

With my operator in `CrashLoopBackOff` state, I cannot delete the BackingStore anymore...

**Comment by guymguym** [comment]
Hey @pranavgaikwad!
That's really helpful, thanks.

So you just got hit by some bugs that should be fixed (sorry about that):
1. The first panic is due to missing nil checking on S3Options.
2. In a CrashLoop situation any resource with the finalizer will not complete the deletion until you will manually `kubectl patch backingstore bstore-s3-00 -p '{"metadata":{"finalizers":null}}'`. Perhaps there could be a way to separate the finalizers handling to a separate container to avoid getting stuck by crash loops? What do you think?
3. The message was using the secret. Thanks for the PR to fix it.

Will fix the nil checking.
