### ISSUE TITLE
Deleting NooBaa CR leads to CrashLoopBackOff of noobaa-operator

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-operator#466]
### Environment info
- NooBaa Version: master+681687b534
- Platform: OKD 4.5

### Actual behavior
1. Delete NooBaa CR
2. Everything is deleted, except the noobaa-default-backing-store
3. Noobaa-operator keeps crashing and doesn't remove the "noobaa.io/finalizer" from the backing-store

### Expected behavior
1. Delete NooBaa CR
2. Everything gets deleted

### More information - Screenshots / Logs / Other output
noobaa-operator output:
```
time="2020-11-25T08:41:00Z" level=info msg="✅ Exists: BackingStore \"noobaa-default-backing-store\"\n"
time="2020-11-25T08:41:00Z" level=info msg="✅ Exists: NooBaa \"noobaa\"\n"
time="2020-11-25T08:41:00Z" level=info msg="✅ Exists: NooBaa \"noobaa\"\n"
time="2020-11-25T08:41:00Z" level=info msg="❌ Not Found:  \"noobaa-default-backing-store-noobaa-noobaa\"\n"
time="2020-11-25T08:41:00Z" level=info msg="❌ Not Found: Secret \"backing-store-pv-pool-noobaa-default-backing-store\"\n"
time="2020-11-25T08:41:00Z" level=panic msg="☠️  Panic Attack: [Invalid] NooBaa.noobaa.io \"noobaa\" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"noobaa.io/graceful_finalizer\"}"
E1125 08:41:00.914521       1 runtime.go:78] Observed a panic: &logrus.Entry{Logger:(*logrus.Logger)(0xc00020e230), Data:logrus.Fields{}, Time:time.Time{wall:0xbfe7a4073680b28c, ext:5491982707, loc:(*time.Location)(0x2ca2ea0)}, Level:0x0, Caller:(*runtime.Frame)(nil), Message:"☠️  Panic Attack: [Invalid] NooBaa.noobaa.io \"noobaa\" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"noobaa.io/graceful_finalizer\"}", Buffer:(*bytes.Buffer)(nil), Context:(*context.emptyCtx)(0xc000044268), err:""} (&{0xc00020e230 map[] 2020-11-25 08:41:00.91440398 +0000 UTC m=+5.491982707 panic <nil> ☠️  Panic Attack: [Invalid] NooBaa.noobaa.io "noobaa" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{"noobaa.io/graceful_finalizer"} <nil> context.TODO })
goroutine 864 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d206e0, 0xc0002b40e0)
	noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1d206e0, 0xc0002b40e0)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/sirupsen/logrus.Entry.log(0xc00020e230, 0xc00059bd10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:261 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc0000f5dc0, 0x0, 0xc000d25910, 0x1, 0x1)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:289 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc0000f5dc0, 0x0, 0x1d7dafb, 0x1d, 0xc000d25970, 0x2, 0x2)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:335 +0xe5
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:373
github.com/noobaa/noobaa-operator/v2/pkg/util.Panic(0x2008ee0, 0xc0004b2c80)
	noobaa-operator/pkg/util/util.go:560 +0xf3
github.com/noobaa/noobaa-operator/v2/pkg/util.KubeUpdate(0x2017260, 0xc000278480, 0x1d7b56b)
	noobaa-operator/pkg/util/util.go:322 +0x2fd
github.com/noobaa/noobaa-operator/v2/pkg/system.(*Reconciler).Reconcile(0xc000618820, 0xb, 0xc000a31bc4, 0x6, 0x205f540)
	noobaa-operator/pkg/system/reconciler.go:278 +0x76e
github.com/noobaa/noobaa-operator/v2/pkg/controller/noobaa.Add.func1(0xc000a31be0, 0xb, 0xc000a31bc4, 0x6, 0x4cc206, 0x5fbe189c, 0x20a3008b, 0x49369ffffd62)
	noobaa-operator/pkg/controller/noobaa/noobaa_controller.go:50 +0x113
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc0006ca720, 0xc000a31be0, 0xb, 0xc000a31bc4, 0x6, 0x1317ab03e, 0xc000abb290, 0xc000dc4128, 0xc000dc4120)
	noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:93 +0x4e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000049080, 0x1b649a0, 0xc0003e21a0, 0x0)
	noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000049080, 0x0)
	noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000049080)
	noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000af5290)
	noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000af5290, 0x3b9aca00, 0x0, 0x1, 0xc00080c1e0)
	noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(0xc000af5290, 0x3b9aca00, 0xc00080c1e0)
	noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x32d
panic: (*logrus.Entry) 0xc0002b40e0 [recovered]
	panic: (*logrus.Entry) 0xc0002b40e0

goroutine 864 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1d206e0, 0xc0002b40e0)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/sirupsen/logrus.Entry.log(0xc00020e230, 0xc00059bd10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:261 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc0000f5dc0, 0x0, 0xc000d25910, 0x1, 0x1)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:289 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc0000f5dc0, 0x0, 0x1d7dafb, 0x1d, 0xc000d25970, 0x2, 0x2)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:335 +0xe5
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:373
github.com/noobaa/noobaa-operator/v2/pkg/util.Panic(0x2008ee0, 0xc0004b2c80)
	noobaa-operator/pkg/util/util.go:560 +0xf3
github.com/noobaa/noobaa-operator/v2/pkg/util.KubeUpdate(0x2017260, 0xc000278480, 0x1d7b56b)
	noobaa-operator/pkg/util/util.go:322 +0x2fd
github.com/noobaa/noobaa-operator/v2/pkg/system.(*Reconciler).Reconcile(0xc000618820, 0xb, 0xc000a31bc4, 0x6, 0x205f540)
	noobaa-operator/pkg/system/reconciler.go:278 +0x76e
github.com/noobaa/noobaa-operator/v2/pkg/controller/noobaa.Add.func1(0xc000a31be0, 0xb, 0xc000a31bc4, 0x6, 0x4cc206, 0x5fbe189c, 0x20a3008b, 0x49369ffffd62)
	noobaa-operator/pkg/controller/noobaa/noobaa_controller.go:50 +0x113
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc0006ca720, 0xc000a31be0, 0xb, 0xc000a31bc4, 0x6, 0x1317ab03e, 0xc000abb290, 0xc000dc4128, 0xc000dc4120)
	noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:93 +0x4e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000049080, 0x1b649a0, 0xc0003e21a0, 0x0)
	noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000049080, 0x0)
	noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000049080)
	noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000af5290)
	noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000af5290, 0x3b9aca00, 0x0, 0x1, 0xc00080c1e0)
	noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(0xc000af5290, 0x3b9aca00, 0xc00080c1e0)
	noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x32d
```

**Comment by guymguym** [comment]
@romayalon see above ^ related to graceful finalizer...

**Comment by romayalon** [comment]
@lallinger-arbeit @guymguym checked it on minikube with the latest master and I don't see this problem.
@lallinger-arbeit please check it on your side and let us know if this problem still occurs.

**Comment by lallinger-arbeit** [comment]
@guymguym just tested it with the current master, it still happens, but only if i delete the NooBaa CR via ArgoCD if i use oc or kubectl delete -f everything works.. @romayalon said you could have some insight

**Comment by guymguym** [comment]
@romayalon @lallinger-arbeit maybe try to toggle the relevant options to kubectl delete such as `--force`, `--grace-period`, `--now`, `--timeout`, `--wait`, etc - maybe argo uses options like these on the API calls?

**Comment by lallinger-arbeit** [comment]
@liranmauda this still happens but it's mostly just an annoyance, so low priority

**Comment by lallinger-arbeit** [comment]
my fault, i accidentally did not use the current master of the operator but 5.8.0 (even though i thought i did use it..). this does not happen anymore with 0930d7f036200cb6e1370116c17d0e334e3334ec
