### ISSUE TITLE
Noobaa admin reset password not working

### ISSUE THREAD

**Issue by nilesh-bhosale** [noobaa/noobaa-operator#644]
### Environment info
- NooBaa Operator Version: **master-20210601**
- Platform: **OpenShift 4.7.4**

### Actual behavior
```
# noobaa api account_api reset_password '{"email":"admin@noobaa.io", "verification_password": "yd128wX/xR7U4U5cwDXQCA==", "password": "TmV3UGFzc3cwcmQ="}'
I0602 03:41:13.763545  177760 request.go:645] Throttling request took 1.005168962s, request: GET:https://oauth-openshift.apps.hpo-nb.cp
.fyre.ibm.com:6443/apis/admissionregistration.k8s.io/v1beta1?timeout=32s
INFO[0001] ✅ Exists: NooBaa "noobaa"
INFO[0001] ✅ Exists: Service "noobaa-mgmt"
INFO[0001] ✅ Exists: Secret "noobaa-operator"
INFO[0001] ✅ Exists: Secret "noobaa-admin"
INFO[0001] ✈️  RPC: account.reset_password() Request: map[email:admin@noobaa.io password:TmV3UGFzc3cwcmQ= verification_password:yd128wX
/xR7U4U5cwDXQCA==]
WARN[0001] RPC: GetConnection creating connection to wss://localhost:46401/rpc/ 0xc0005a95e0
INFO[0001] RPC: Connecting websocket (0xc0005a95e0) &{RPC:0xc000184d70 Address:wss://localhost:46401/rpc/ State:init WS:<nil> PendingRe
quests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] RPC: Connected websocket (0xc0005a95e0) &{RPC:0xc000184d70 Address:wss://localhost:46401/rpc/ State:init WS:<nil> PendingReq
uests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
ERRO[0001] ⚠️  RPC: account.reset_password() Response Error: Code=INTERNAL Message=Cannot read property 'unwrap' of undefined
FATA[0001] ❌ Cannot read property 'unwrap' of undefined
```

### Expected behavior
1. Password can be reset for the admin, using the account_api reset_password method.

### Steps to reproduce
1. As mentioned above

### More information - Screenshots / Logs / Other output
Logs from noobaa-core pod:
```
Jun-2 11:40:41.694 [WebServer/34] [ERROR] CONSOLE:: RPC._on_request: ERROR srv account_api.reset_password reqid wss://localhost:39399/rpc/-0 connid ws://[::ffff:127.0.0.1]:59892/(2g9ve96o4) TypeError: Cannot read property 'unwrap' of undefined
    at /root/node_modules/noobaa-core/src/server/system_services/account_server.js:1453:104
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /root/node_modules/noobaa-core/src/rpc/rpc.js:340:32
    at async RPC._on_request (/root/node_modules/noobaa-core/src/rpc/rpc.js:348:25)
```

May be some issue here:
https://github.com/noobaa/noobaa-core/blob/master/src/server/system_services/account_server.js#L1453

**Comment by guymguym** [comment]
so `req.account.password`  is undefined which happens because by default the CLI api calls use the token of the operator account as the calling account, but the operator account doesn't have a password.

I think we should just allow the operator to bypass this check. 
WDYT @nimrod-becker ?

**Comment by nimrod-becker** [comment]
@guymguym sure.
But do we impose a more strict approach to prevent just anyone from changing the admin password?
We have been talking about an option of making the CLI work in authed mode (so you would need to provide, a secret, a token, a password, something) to be able to call the different APIs and the actions.
Maybe we can bypass this check when we are in such a mode.

**Comment by nilesh-bhosale** [comment]
Verified with:

```
# noobaa api account_api reset_password '{"email":"admin@noobaa.io", "verification_password": "
JGRFdnQDiYSDqeNYvTzBDQ==", "password": "TmV3UGFzc3cwcmQ="}'
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ✅ Exists: Service "noobaa-mgmt"
INFO[0000] ✅ Exists: Secret "noobaa-operator"
INFO[0000] ✅ Exists: Secret "noobaa-admin"
INFO[0000] ✈️  RPC: account.reset_password() Request: map[email:admin@noobaa.io password:TmV3UGFzc3cwcmQ= verification_password:JGRFdnQ
DiYSDqeNYvTzBDQ==]
WARN[0000] RPC: GetConnection creating connection to wss://localhost:34793/rpc/ 0xc000a1df80
INFO[0000] RPC: Connecting websocket (0xc000a1df80) &{RPC:0xc00035ce60 Address:wss://localhost:34793/rpc/ State:init WS:<nil> PendingRe
quests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s cancelPings:<nil>}
INFO[0000] RPC: Connected websocket (0xc000a1df80) &{RPC:0xc00035ce60 Address:wss://localhost:34793/rpc/ State:init WS:<nil> PendingReq
uests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s cancelPings:<nil>}
INFO[0001] ✅ RPC: account.reset_password() Response OK: took 602.9ms
null
```
Then tried getting an auth token using the old password:
```
# curl -k https://10.17.95.61:30132/rpc/ -sd '{
  "api": "auth_api",
  "method": "create_auth",
  "params": {
"role": "admin",
"system": "noobaa",
"email": "admin@noobaa.io",
"password": "JGRFdnQDiYSDqeNYvTzBDQ=="
  }
}'
{"op":"res","reqid":"1@https://::ffff:10.254.16.1:43915(1jkmlmi4y8)","took":74.3586620092392,"error":{"message":"credentials not found","rpc_code":"UNAUTHORIZED"}}
```
As expected this did not work and we got 'UNAUTHORIZED' response.

When tried with the new password:
```
# curl -k https://10.17.95.61:30132/rpc/ -sd '{
>   "api": "auth_api",
>   "method": "create_auth",
>   "params": {
> "role": "admin",
> "system": "noobaa",
> "email": "admin@noobaa.io",
> "password": "TmV3UGFzc3cwcmQ="
>   }
> }'
{"op":"res","reqid":"1@https://::ffff:10.254.16.1:63489(1jls7slmyz)","took":71.06210398674011,"reply":{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoiNjI0YWQ3ZGUxZWQyMjMwMDI5ZjU3YjIwIiwic3lzdGVtX2lkIjoiNjI0YWQ3ZGUxZWQyMjMwMDI5ZjU3YjIxIiwicm9sZSI6ImFkbWluIiwiYXV0aG9yaXplZF9ieSI6Im5vb2JhYSIsImlhdCI6MTY0OTIyODk1MH0.kfZplzOs1RCTnWDI4AJAoiPtqu3WIdB2dVL1cVneQHI","info":{"authorized_by":"noobaa","role":"admin","account":{"name":"noobaa","email":"admin@noobaa.io"},"system":{"name":"noobaa"}}}}
```
Got a valid token response as expected.

So far looks good.

But, noobaa status still seen showing old password for the admin account:
```
# noobaa status 
...
...
#--------------------#
#- Mgmt Credentials -#
#--------------------#

email    : admin@noobaa.io
password : JGRFdnQDiYSDqeNYvTzBDQ==
...
...
```

So, mostly looks good to close as *verified*, but the last bit still doesn't look as expected.
@nimrod-becker any thoughts?

**Comment by liranmauda** [comment]
@nilesh-bhosale 
You should do it via NooBaa CLI or mock it's flow. 
this PR (https://github.com/noobaa/noobaa-operator/pull/808) solves it but it is not backported to 5.9
When you are calling the RPC directly it is not handling the kubernetes object (in this case secret).
The PR adding the call for the RPC and the handle for the secret.

I think this issue is verified and can be closed 😄 
WDYT?

**Comment by nilesh-bhosale** [comment]
Thanks @liranmauda
