### ISSUE TITLE
Failing to generate CSV with 'Panic Attack: [] invalid configuration: no configuration has been provided'

### ISSUE THREAD

**Issue by andrewschoen** [noobaa/noobaa-operator#67]
The openshift/ocs-operator project has a script that generates a combined CSV from all the projects in use. The script is now failing while trying to get a CSV from noobaa-operator.

Please refer to the openshift issue here: https://github.com/openshift/ocs-operator/issues/174

Relevant log output from noobaa-operator:

```
$ docker run --rm -it quay.io/rhceph-dev/mcg-operator:4.2-87 olm csv yaml

PANI[0000] ☠️  Panic Attack: [] invalid configuration: no configuration has been provided 
panic: (*logrus.Entry) (0x182df40,0xc00019b420)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000b6420, 0xc00042fc50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2cf
github.com/sirupsen/logrus.(*Entry).Log(0xc00019acb0, 0xc000000000, 0xc0000dfd90, 0x1, 0x1)
	/vendor/github.com/sirupsen/logrus/entry.go:268 +0xc8
github.com/sirupsen/logrus.(*Entry).Logf(0xc00019acb0, 0x0, 0x187a9c7, 0x1d, 0xc0000dfe40, 0x2, 0x2)
	/vendor/github.com/sirupsen/logrus/entry.go:314 +0xfc
github.com/sirupsen/logrus.(*Entry).Panicf(0xc00019acb0, 0x187a9c7, 0x1d, 0xc0000dfe40, 0x2, 0x2)
	/vendor/github.com/sirupsen/logrus/entry.go:352 +0x65
github.com/noobaa/noobaa-operator/pkg/util.Panic(0x1ab0180, 0xc0003f7800)
	/pkg/util/util.go:409 +0x105
github.com/noobaa/noobaa-operator/pkg/util.CurrentNamespace(0x0, 0x0)
	/pkg/util/util.go:450 +0x111
github.com/noobaa/noobaa-operator/pkg/options.init.0()
	/pkg/options/options.go:90 +0x2c4
```

**Comment by guymguym** [comment]
Hi @andrewschoen CC @davidvossel
Sorry about this - this is caused since we now try to detect the current namespace on startup and there is no default kube config file inside the container image.

This will be fixed easily but in the meanwhile you can use this workaround:

```
$ cat dummy.kubeconfig
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:6443
  name: dummy
contexts:
- context:
    cluster: dummy
    namespace: dummy
    user: dummy
  name: dummy
current-context: dummy
kind: Config
preferences: {}
users:
- name: dummy

$ docker run --rm -it -v $PWD/dummy.kubeconfig:/.kube/config noobaa/noobaa-operator:2.0.0 olm csv
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
...
```

BTW the command to get the csv is now simply `olm csv` and no need to add `yaml` at the end.
