### ISSUE TITLE
bucket_api.create_bucket fails to create bucket either nsfs/normal type

### ISSUE THREAD

**Issue by bssrikanth** [noobaa/noobaa-operator#673]
### Environment info
INFO[0000] CLI version: 5.9.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210616 [but I have seen same issue on 0622 build as well]
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0 

OCP:
Server Version: 4.7.12
Kubernetes Version: v1.20.0+df9c838

### Actual behavior
Observed that bucket_api.create_bucket fails to create buckets after user deletes all buckets and starts over with bucket creations again. 

### Expected behavior
Observed that bucket_api.create_bucket should succeed to create buckets even after user deletes all buckets and starts over with bucket creations. 

### Steps to reproduce
1. Delete all buckets which are shown under `noobaa bucket list` using `noobaa bucket delete <name>` command.
2. Attempt to create a new nsfs bucket using bucket_api.create_bucket
```
noobaa api bucket_api create_bucket '{"name":"bucket1user01","namespace":{"write_resource":{"resource":"fs1","path":"bucket1"},"read_resources":[{"resource":"fs1","path":"bucket1"}]}}'
```
or
``` 
noobaa api bucket_api create_bucket '{"name":"bucket1user01"}'
```
It fails with below error
```
FATA[0001] ❌ Cannot read property 'bucket1user01#kqbuft7c' of undefined 
```
More logs in below section.

3. However I could create buckets via the accounts created.
```
# AWS_ACCESS_KEY_ID=T65pA58Fh4na2upZoW1N AWS_SECRET_ACCESS_KEY=sT6t6CcUyCmpKtjZyqoSZSB3e+3YOE80Fyn7lMbH aws --endpoint https://s3-noobaa.apps.hpoocpci.cp.fyre.ibm.com --no-verify-ssl s3 mb s3://user01bucket
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.hpoocpci.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket: user01bucket

# noobaa bucket list
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: bucket.list_buckets() Request: <nil> 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:41053/rpc/ 0xc00072df40 
INFO[0001] RPC: Connecting websocket (0xc00072df40) &{RPC:0xc0004ff270 Address:wss://localhost:41053/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc00072df40) &{RPC:0xc0004ff270 Address:wss://localhost:41053/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: bucket.list_buckets() Response OK: took 0.3ms 

BUCKET-NAME    
user01bucket   

# noobaa bucket status user01bucket
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: bucket.read_bucket() Request: {Name:user01bucket} 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:44173/rpc/ 0xc00007ce60 
INFO[0001] RPC: Connecting websocket (0xc00007ce60) &{RPC:0xc00059c500 Address:wss://localhost:44173/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc00007ce60) &{RPC:0xc00059c500 Address:wss://localhost:44173/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: bucket.read_bucket() Response OK: took 5.3ms 

Bucket status:
  Bucket                 : user01bucket
  Type                   : NAMESPACE
  Mode                   : OPTIMAL
  Num Objects            : 0
  Data Size              : 0.000 B
  Data Size Reduced      : 0.000 B
  Data Space Avail       : 0.000 B

```
### More information - Screenshots / Logs / Other output
```
[root@hpoocpci-inf ~]# noobaa bucket list
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: bucket.list_buckets() Request: <nil> 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:35291/rpc/ 0xc000a6c0a0 
INFO[0001] RPC: Connecting websocket (0xc000a6c0a0) &{RPC:0xc000534500 Address:wss://localhost:35291/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc000a6c0a0) &{RPC:0xc000534500 Address:wss://localhost:35291/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: bucket.list_buckets() Response OK: took 0.3ms 
No buckets found.
[root@hpoocpci-inf ~]# noobaa api bucket_api create_bucket '{"name":"bucket1user01","namespace":{"write_resource":{"resource":"fs1","path":"bucket1"},"read_resources":[{"resource":"fs1","path":"bucket1"}]}}'
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: bucket.create_bucket() Request: map[name:bucket1user01 namespace:map[read_resources:[map[path:bucket1 resource:fs1]] write_resource:map[path:bucket1 resource:fs1]]] 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:34345/rpc/ 0xc00003bb30 
INFO[0001] RPC: Connecting websocket (0xc00003bb30) &{RPC:0xc00058b090 Address:wss://localhost:34345/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc00003bb30) &{RPC:0xc00058b090 Address:wss://localhost:34345/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
ERRO[0001] ⚠️  RPC: bucket.create_bucket() Response Error: Code=INTERNAL Message=Cannot read property 'bucket1user01#kqbuft7c' of undefined 
FATA[0001] ❌ Cannot read property 'bucket1user01#kqbuft7c' of undefined 

# noobaa bucket create temp
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: bucket.create_bucket() Request: {Name:temp Tiering: BucketClaim:<nil> Namespace:<nil>} 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:40653/rpc/ 0xc000437b30 
INFO[0001] RPC: Connecting websocket (0xc000437b30) &{RPC:0xc0004366e0 Address:wss://localhost:40653/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc000437b30) &{RPC:0xc0004366e0 Address:wss://localhost:40653/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
ERRO[0001] ⚠️  RPC: bucket.create_bucket() Response Error: Code=INTERNAL Message=Cannot read property 'temp#kqbwt6y7' of undefined 
FATA[0001] Cannot read property 'temp#kqbwt6y7' of undefined 

noobaa-core pod logs:

Jun-25 4:50:18.380 [WebServer/36] [ERROR] CONSOLE:: RPC._on_request: ERROR srv bucket_api.create_bucket reqid wss://localhost:33227/rpc/-0 connid ws://[::ffff:127.0.0.1]:47566/(eg0xy113e) TypeError: Cannot read property 'bucket1user01#kqbuvpfv' of undefined
    at Object.check_tier_exists (/root/node_modules/noobaa-core/src/server/system_services/tier_server.js:864:33)
    at Object.create_bucket (/root/node_modules/noobaa-core/src/server/system_services/bucket_server.js:129:21)
    at Object.server_func (/root/node_modules/noobaa-core/src/rpc/rpc.js:113:48)
    at /root/node_modules/noobaa-core/src/rpc/rpc.js:340:46
    at RPC._on_request (/root/node_modules/noobaa-core/src/rpc/rpc.js:345:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by nilesh-bhosale** [comment]
This does not happen immediately, but happens once you play around with this functionality for a while.
Create, namespacestore resources, create buckets using those. Delete all buckets including the `first.bucket`, then try to create buckets again.
another variation, delete all namespacestore resources after deleting buckets as described above, and then create the namespacestore resources again and then try creating buckets.

Note, that in these experiments, the bucket is created using sub-path under the resource.
I suspect, Noobaa code is failing to concatenate the sub-path to the resource path, while trying to access the bucket dir on filesystem.

**Comment by nilesh-bhosale** [comment]
@nimrod-becker ^^^

**Comment by jackyalbo** [comment]
@nilesh-bhosale I'm taking a look on this - I will have a PR shortly

**Comment by jackyalbo** [comment]
@nilesh-bhosale The above PR will fix the issues in the original issue - where you don't have any buckets in the system and you try to create a new one and fails. If you still see some specific issue about sub-paths please raise a new one.

**Comment by bssrikanth** [comment]
Which build of noobaa would have this fix?

**Comment by nimrod-becker** [comment]
-20210630

**Comment by bssrikanth** [comment]
verified on latest noobaa build, issue reported here is fixed.
```
[root@hpoocpci-inf HPO]# noobaa api bucket_api list_buckets '{}'
I0712 01:04:55.371459  259195 request.go:645] Throttling request took 1.017287998s, request: GET:https://api.hpoocpci.cp.fyre.ibm.com:6443/apis/operator.openshift.io/v1alpha1?timeout=32s
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: bucket.list_buckets() Request: map[] 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:33873/rpc/ 0xc0000c9810 
INFO[0001] RPC: Connecting websocket (0xc0000c9810) &{RPC:0xc000350820 Address:wss://localhost:33873/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc0000c9810) &{RPC:0xc000350820 Address:wss://localhost:33873/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: bucket.list_buckets() Response OK: took 0.3ms 
buckets: []

[root@hpoocpci-inf HPO]# noobaa api bucket_api create_bucket '{"name":"export1","namespace":{"write_resource":{"resource":"fs10","path":""},"read_resources":[{"resource":"fs10","path":""}]}}'
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: bucket.create_bucket() Request: map[name:export1 namespace:map[read_resources:[map[path: resource:fs10]] write_resource:map[path: resource:fs10]]] 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:33361/rpc/ 0xc000289540 
INFO[0001] RPC: Connecting websocket (0xc000289540) &{RPC:0xc0000f2fa0 Address:wss://localhost:33361/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc000289540) &{RPC:0xc0000f2fa0 Address:wss://localhost:33361/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: bucket.create_bucket() Response OK: took 32.7ms 
bucket_type: NAMESPACE
data:
  available_for_upload: 0
  free: 0
  last_update: 1626077023359
  size: 0
  size_reduced: 0
host_tolerance: 0
mode: OPTIMAL
name: export1
namespace:
  read_resources:
  - path: ""
    resource: fs10
  should_create_underlying_storage: false
  write_resource:
    path: ""
    resource: fs10
node_tolerance: 0
num_objects:
  last_update: 1626076920000
  value: 0
owner_account:
  email: operator@noobaa.io
  id: 60ebd8c87ffdeb00285607c1
stats_by_type: []
storage:
  last_update: 1626077023359
  values:
    free: 0
    total: 0
    used: 0
    used_other: 0
tag: ""
tiering:
  data: {}
  mode: NO_RESOURCES_INTERNAL
  name: export1#kr0cbwqz
  tiers:
  - disabled: false
    mode: OPTIMAL
    order: 0
    spillover: false
    tier: export1#kr0cbwqz
triggers: []
usage_by_pool:
  last_update: 1626076920000
  pools: []
versioning: DISABLED
writable: false

[root@hpoocpci-inf HPO]# noobaa api bucket_api list_buckets '{}'
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: bucket.list_buckets() Request: map[] 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:46775/rpc/ 0xc0009deaf0 
INFO[0001] RPC: Connecting websocket (0xc0009deaf0) &{RPC:0xc00050c3c0 Address:wss://localhost:46775/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc0009deaf0) &{RPC:0xc00050c3c0 Address:wss://localhost:46775/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: bucket.list_buckets() Response OK: took 0.4ms 
buckets:
- name: export1

[root@hpoocpci-inf HPO]# noobaa bucket status export1
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: bucket.read_bucket() Request: {Name:export1} 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:37943/rpc/ 0xc0005cdef0 
INFO[0001] RPC: Connecting websocket (0xc0005cdef0) &{RPC:0xc000105360 Address:wss://localhost:37943/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc0005cdef0) &{RPC:0xc000105360 Address:wss://localhost:37943/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: bucket.read_bucket() Response OK: took 4.9ms 

Bucket status:
  Bucket                 : export1
  Type                   : NAMESPACE
  Mode                   : OPTIMAL
  Num Objects            : N/A
  Data Size              : N/A
  Data Size Reduced      : N/A
  Data Space Avail       : N/A

```
