### ISSUE TITLE
Default backingstore has no secret

### ISSUE THREAD

**Issue by igorpick** [noobaa/noobaa-operator#683]
### Environment info
- NooBaa Operator Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. The default backingstore noobaa-default-backing-store has no a secret configuration.
2. It causes to panic message in noobaa cli when getting the backingstore status.

### Expected behavior
1.  The default backingstore is configured with secret backing-store-pv-pool-noobaa-default-backing-store name

### Steps to reproduce
1. noobaa install
2. noobaa backingstore status noobaa-default-backing-store

### More information - Screenshots / Logs / Other output
```
$kubectl get backingstores.noobaa.io/noobaa-default-backing-store -o yaml

kind: BackingStore
metadata:
  creationTimestamp: "2021-07-05T07:55:06Z"
  finalizers:
  - noobaa.io/finalizer
  generation: 1
  labels:
    app: noobaa
  name: noobaa-default-backing-store
  namespace: noobaa
  ownerReferences:
  - apiVersion: noobaa.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: NooBaa
    name: noobaa
    uid: 92b832fc-0001-4570-bba8-ee8b0c2937f5
  resourceVersion: "215684"
  uid: c488a9db-8321-4a8b-a9f4-df2774ce9a5d
spec:
  pvPool:
    numVolumes: 1
    resources:
      requests:
        storage: 50Gi
    secret: {}
  type: pv-pool
status:
  conditions:
  - lastHeartbeatTime: "2021-07-05T07:55:06Z"
    lastTransitionTime: "2021-07-08T11:55:38Z"
    message: BackingStorePhaseReady
    reason: 'Backing store mode: LOW_CAPACITY'
    status: "True"
    type: Available
  - lastHeartbeatTime: "2021-07-05T07:55:06Z"
    lastTransitionTime: "2021-07-08T11:55:38Z"
    message: BackingStorePhaseReady
    reason: 'Backing store mode: LOW_CAPACITY'
    status: "False"
    type: Progressing
  - lastHeartbeatTime: "2021-07-05T07:55:06Z"
    lastTransitionTime: "2021-07-08T11:55:37Z"
    message: BackingStorePhaseReady
    reason: 'Backing store mode: LOW_CAPACITY'
    status: "False"
    type: Degraded
  - lastHeartbeatTime: "2021-07-05T07:55:06Z"
    lastTransitionTime: "2021-07-08T11:55:38Z"
    message: BackingStorePhaseReady
    reason: 'Backing store mode: LOW_CAPACITY'
    status: "True"
    type: Upgradeable
  mode:
    modeCode: LOW_CAPACITY
    timeStamp: 2021-07-08 11:55:37.93031022 +0000 UTC m=+1893.128699389
  phase: Ready

$kubectl get secret | grep default
backing-store-pv-pool-noobaa-default-backing-store   Opaque                                1      3d4h

$noobaa backingstore status noobaa-default-backing-store

INFO[0000] ✅ Exists: BackingStore "noobaa-default-backing-store"
PANI[0000] ☠️  Panic Attack: [] resource name may not be empty
panic: (*logrus.Entry) 0xc0004d62a0

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc00026c540, 0xc0002c3b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/igorpick/workspace/noobaa/noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc0004fc690, 0x0, 0xc000c9fad0, 0x1, 0x1)
	/Users/igorpick/workspace/noobaa/noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc0004fc690, 0x0, 0x2a0aeea, 0x1d, 0xc000c9fb28, 0x2, 0x2)
	/Users/igorpick/workspace/noobaa/noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:333 +0xe5
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	/Users/igorpick/workspace/noobaa/noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:371
github.com/noobaa/noobaa-operator/v5/pkg/util.Panic(0x2cfd900, 0xc000566b00)
	/Users/igorpick/workspace/noobaa/noobaa-operator/pkg/util/util.go:638 +0xee
github.com/noobaa/noobaa-operator/v5/pkg/util.KubeCheck(0x2d0f3d0, 0xc0004df040, 0x2d0cf01)
	/Users/igorpick/workspace/noobaa/noobaa-operator/pkg/util/util.go:424 +0x23d
github.com/noobaa/noobaa-operator/v5/pkg/backingstore.RunStatus(0xc0000badc0, 0xc0005a5080, 0x1, 0x1)
	/Users/igorpick/workspace/noobaa/noobaa-operator/pkg/backingstore/backingstore.go:703 +0x2e9
github.com/spf13/cobra.(*Command).execute(0xc0000badc0, 0xc0005a5010, 0x1, 0x1, 0xc0000badc0, 0xc0005a5010)
	/Users/igorpick/workspace/noobaa/noobaa-operator/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b4000, 0x1001570, 0x0, 0x0)
	/Users/igorpick/workspace/noobaa/noobaa-operator/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/igorpick/workspace/noobaa/noobaa-operator/vendor/github.com/spf13/cobra/command.go:887
github.com/noobaa/noobaa-operator/v5/pkg/cli.Run()
	/Users/igorpick/workspace/noobaa/noobaa-operator/pkg/cli/cli.go:55 +0x2a
main.main()
	/Users/igorpick/workspace/noobaa/noobaa-operator/cmd/manager/main.go:14 +0x25
```

**Comment by larsks** [comment]
We're hitting the same error (as is presumably everybody else who has deployed noobaa in the default openshift configuration).
